In [113]:
import pydytuesday
import pandas as pd
import seaborn as sns
import matplotlib as plt


all_recipes = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-16/all_recipes.csv')
cuisines = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-16/cuisines.csv')

In [114]:

all_recipes.head()
cuisines.head()

,name,country,url,author,date_published,ingredients,calories,fat,carbs,protein,avg_rating,total_ratings,reviews,prep_time,cook_time,total_time,servings
0,Saganaki (Flaming Greek Cheese),Greek,https://www.allrecipes.com/recipe/263750/flami...,John Mitzewich,2024-02-07,"1 (4 ounce) package kasseri cheese, 1 tablespo...",391.0,25.0,15.0,16.0,4.8,25.0,22.0,10,5,15,2.0
1,Coney Island Knishes,Jewish,https://www.allrecipes.com/recipe/272334/coney...,John Mitzewich,2024-11-26,"2 ¾ cups all-purpose flour, or more as needed,...",301.0,17.0,31.0,7.0,4.6,10.0,9.0,30,75,180,16.0
2,Diana's Hawaiian Bread Rolls,Australian and New Zealander,https://www.allrecipes.com/recipe/22797/dianas...,CHIPPENDALE,2022-07-14,1 ½ cups warm water (110 degrees F/45 degrees ...,64.0,3.0,9.0,1.0,4.3,126.0,104.0,20,15,180,12.0
3,Chilean Pebre,Chilean,https://www.allrecipes.com/recipe/273763/chile...,Heidi,2025-01-31,"½ cup chopped cilantro, ¼ cup olive oil, ¼ cup...",106.0,9.0,7.0,1.0,5.0,1.0,1.0,10,0,10,6.0
4,Tex-Mex Sheet Cake,Tex-Mex,https://www.allrecipes.com/recipe/22388/tex-me...,Ann,2025-02-18,"2 cups all-purpose flour, 1 ½ cups brown sugar...",449.0,23.0,58.0,7.0,3.8,13.0,11.0,30,15,45,15.0

In [115]:
#Focus on following criterions: country, calories, total_time for cuisines dataset

print(cuisines.info())#print(cuisines.describe())

print(cuisines["country"].isnull().sum())
print(cuisines["calories"].isnull().sum())
print(cuisines["total_time"].isnull().sum())
print(cuisines["avg_rating"].isnull().sum())


#Drop all rows with null entries for calories, avg_rating columns
#Also drop rows where total_time equals 0

clean_cuisines = cuisines.dropna(subset = ["calories", "avg_rating"]).copy()
clean_cuisines = clean_cuisines[~(clean_cuisines['total_time'] == 0)]
print(clean_cuisines.info())

#Change column entries to appropriate data type
clean_cuisines["country"] = clean_cuisines["country"].astype('category')

<class 'pandas.DataFrame'>
RangeIndex: 2218 entries, 0 to 2217
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2218 non-null   str
 1   country         2218 non-null   str
 2   url             2218 non-null   str
 3   author          2218 non-null   str
 4   date_published  2218 non-null   str
 5   ingredients     2217 non-null   str
 6   calories        2186 non-null   float64
 7   fat             2163 non-null   float64
 8   carbs           2183 non-null   float64
 9   protein         2179 non-null   float64
 10  avg_rating      2121 non-null   float64
 11  total_ratings   2121 non-null   float64
 12  reviews         2110 non-null   float64
 13  prep_time       2218 non-null   int64
 14  cook_time       2218 non-null   int64
 15  total_time      2218 non-null   int64
 16  servings        2216 non-null   float64
dtypes: float64(8), int64(3), str(6)
memory usage: 294.7 KB
None
0
32
0
97
<class 'pandas.DataFrame'>
Index: 2043 entries, 0 to 2217
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2043 non-null   str
 1   country         2043 non-null   str
 2   url             2043 non-null   str
 3   author          2043 non-null   str
 4   date_published  2043 non-null   str
 5   ingredients     2043 non-null   str
 6   calories        2043 non-null   float64
 7   fat             2024 non-null   float64
 8   carbs           2040 non-null   float64
 9   protein         2037 non-null   float64
 10  avg_rating      2043 non-null   float64
 11  total_ratings   2043 non-null   float64
 12  reviews         2033 non-null   float64
 13  prep_time       2043 non-null   int64
 14  cook_time       2043 non-null   int64
 15  total_time      2043 non-null   int64
 16  servings        2042 non-null   float64
dtypes: float64(8), int64(3), str(6)
memory usage: 287.3 KB
None

In [ ]:
#We want to calculate the average rating of the recipes for each country
cuisines_by_country = clean_cuisines.groupby("country")['avg_rating'].agg('mean').sort_values(ascending = False).reset_index().copy()
cuisines_by_country.head()

cuisines_by_calories = clean_cuisines[["calories", "avg_rating"]].sort_values('calories').reset_index(drop = True).copy()
cuisines_by_calories.head()

cuisines_by_total_time = clean_cuisines[['total_time', 'avg_rating']].sort_values('total_time').reset_index(drop = True).copy()
cuisines_by_total_time.head()

   calories  avg_rating
0       3.0         4.6
1       3.0         4.9
2       4.0         4.8
3       4.0         4.5
4       4.0         4.7